[project]
name = "ketsuka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Koutako2024", email = "koutako2021@yahoo.co.jp" }
]
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.7.1",
    "ollama>=0.6.2",
]

[project.scripts]
ketsuka = "ketsuka:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
